# Path to the beets library file
# library: library.db

# Directory to which files will be copied/moved when adding them to the library
directory: ~/Music/Imported

plugins: fetchart embedart fromfilename mbsync scrub thumbnails

scrub:
    auto: yes

# threaded speeds things up but may cause crashes
threaded: yes

ui:
    color: yes

format_item: $artist - $album - $track - $title
format_album: $albumartist - $album [$original_year]

import:
    move: yes
    copy: no
    write: yes

    # Controls whether interrupted imports should be resumed
    resume: ask

    # Specifies a filename where the importer’s log should be kept
    log: ~/.config/beets/imported-beets.log

    # A list of locale names to search for preferred aliases
    languages: ['en']

match:
    preferred:
        countries: ['US', 'GB|UK', 'CA']
        media: ['CD', 'Digital Media|File']
        original_year: yes


paths:
    default: $albumartist/$album%aunique{}/$albumartist $track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$albumartist $track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title




# Tip: If you are about to import all of your music you and you have enough space
# you can save some of the tedium by doing a quiet import initially:
# https://news.ycombinator.com/item?id=7337597
#
# 1. Optional: `$ cp -r ~/Music ~/ImportMusic ; mv ~/Music ~/Music.orig`
# 2. enable whatever plugins you want (atleast: chroma fromfilename fetchart)
# 3. Set up config (uncomment below)

# directory: ~/Music_beets
# import:
#     move: yes
#     quiet_fallback: skip
#     log: ~/.config/beets/imported-beets.log

# 4. `$ beet import -q ~/ImportMusic`
